#!/bin/bash
if [[ $1 == 'push' ]]; then
    rclone sync /home/cekingx/Documents/obsidian-rclone google-drive:obsidian-rclone -P
elif [[ $1 == 'pull' ]]; then
    rclone sync google-drive:obsidian-rclone /home/cekingx/Documents/obsidian-rclone -P
else
    echo 'UNKNOW COMMAND'
fi